### ISSUE TITLE
Add `jupyter_contrib_nbextensions` to setup.py as a requirement

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-notebook#80]
I am building a docker image for `sos-notebook` and `sos convert` failed:

```
  File "/opt/miniconda3/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/opt/miniconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/miniconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/miniconda3/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 325, in start
    self.convert_notebooks()
  File "/opt/miniconda3/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 483, in convert_notebooks
    self.exporter = cls(config=self.config)
  File "/opt/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/templateexporter.py", line 243, in __init__
    super(TemplateExporter, self).__init__(config=config, **kw)
  File "/opt/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 105, in __init__
    self._init_preprocessors()
  File "/opt/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 259, in _init_preprocessors
    self.register_preprocessor(preprocessor, enabled=True)
  File "/opt/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 220, in register_preprocessor
    preprocessor_cls = import_item(preprocessor)
  File "/opt/miniconda3/lib/python3.6/site-packages/traitlets/utils/importstring.py", line 34, in import_item
    module = __import__(package, fromlist=[obj])
ModuleNotFoundError: No module named 'jupyter_contrib_nbextensions'
```

So we should add `jupyter_contrib_nbextensions` as part of required package? What else do you think we are missing?

**Comment by BoPeng** [comment]
I sometimes see this but it was only a warning message.. it should be easy to add it as a requirement though.

**Comment by gaow** [comment]
Okay, but I guess that warning is not when you run `sos convert ... --template sos-report`, because I now confirm in that case it is an error message instead? It would be good to add it to `setup.py` anyways.

**Comment by BoPeng** [comment]
So the error only happens with the `--template` option?

**Comment by gaow** [comment]
Yes exactly. Sorry I should have made it clear in my other post.

**Comment by BoPeng** [comment]
I actually do not know what is going on here because `sos` eventually calls `jupyter nbconvert`

**Comment by gaow** [comment]
After I made `jupyter_contrib_nbextensions` a dependency I've fixed the issue with my docker image. I never had this issue with my installed version. My docker image just did `pip install sos sos-notebook` on a vanilla `conda` installation.

**Comment by BoPeng** [comment]
OK. Please make the change.

**Comment by BoPeng** [comment]
Comparing https://ci.appveyor.com/project/BoPeng/sos-notebook/build/1.0.221 (success) and https://ci.appveyor.com/project/BoPeng/sos-notebook/build/1.0.299 (fail), I can see that 0.221 is trying to build `lxml` and failed. Let me see if the removal of `jupyter_contrib_nbextension` helps.

**Comment by BoPeng** [comment]
it is proven that `jupyter_contrib_nbextension` blocks the windows tests (https://ci.appveyor.com/project/BoPeng/sos-notebook/build/1.0.301). The tests still fail due to `Kernel died before ...` which has been troubling me for a long time and appears to be caused by relative weak CPU power of the testing environment, but at least the tests are again running.

I would suggest that you install `jupyter_contrib_nbextension` separately for your docker container. Or we could make it a non-windows dependency if you prefer.

**Comment by BoPeng** [comment]
I experienced the same problem but it turns out that I have this module list in the nbconvert configuration file.
